# Referred to: https://github.com/greenplum-db/gpdb/blob/master/.travis.yml
language: cpp
sudo: false

addons:
    apt:
        config:
            retries: true
        sources: &common_sources
            - ubuntu-toolchain-r-test
        packages: &common_packages
            - gcc-7
            - g++-7

matrix:
    include:
        - os: linux
          dist: bionic
          compiler: gcc
          env:
              - T=release C=""
              - OVERRIDE_CC="CC=gcc-7" OVERRIDE_CXX="CXX=g++-7"
          addons:
              apt:
                  sources:
                      - *common_sources
                  packages:
                      - *common_packages

before_install:
    - eval "${OVERRIDE_CC}"
    - eval "${OVERRIDE_CXX}"

script:
  - g++ ./Delegate/TestDelegate.cpp -std=c++11 -o TestDelegate
  - ./TestDelegate

#after_success: 
  # this need compiler flags: -fprofile-arcs -ftest-coverag
  # example: https://github.com/codecov/example-cpp11
  # - bash <(curl -s https://codecov.io/bash)